### ISSUE TITLE
Move password encryption function to AuthUtils instead of calling BC.HashPassword directly

### ISSUE THREAD

**Issue by Myheartdies** [choutianxius/aggie-rent#28]

**Comment by choutianxius** [comment]
Why? `AuthUtils` was created to reduce redundant code in auth and user services. If we do this, should we even create a dedicated method for generated unique IDs to replace `Guid.NewGuid().ToString`?

**Comment by Myheartdies** [comment]
> Why? `AuthUtils` was created to reduce redundant code in auth and user services. If we do this, should we even create a dedicated method for generated unique IDs to replace `Guid.NewGuid().ToString`?

I suggest this change not to reduce the amount of code written but to improve maintainability, as in if the library, method or algorithm for hashing passwords changes in the future, this eliminated the need to modify them line by line, instead we'll only need to change it in an encapsulated function.

However I seem to have misunderstood the function of `AuthUtils`, and considering that we have no plan to make further changes to the password hashing method after the current one, I do agree we don't need to do this.
